### ISSUE TITLE
Validating arrays of objects in JSON

### ISSUE THREAD

**Issue by jtiala** [DavidePastore/Slim-Validation#25]
I'm trying to validate the following JSON body
```javascript
{
	"date": "2000-01-01",
	"arrayOfObjects": [
		{
			"id": 1,
			"name": "one"
		},
		{
			"id": 2,
			"name": "two"
		}
	]
}
```
with the following validators
```php
$validators = [
	'date' => v::date()->notEmpty(),
	'arrayOfObjects': [
		[
			'id' => v::intVal()->positive()->notEmpty(),
			'name' => v::alnum()->notEmpty()
		]
	]
];
```

This seems to validate only the first object and ingnore the rest. If I change the first id to a negative integer for example, I get error message like 

> arrayOfObjects.0.id": ["-12 must be positive"]

but when changing the second object, it validates as valid.

Am I doing something wrong, or doesn't the library support JSON arrays at all?

**Comment by DavidePastore** [comment]
Hi @jtiala , sorry for the late reply. The problem here is your configuration of the validators. [Respect Validation](https://github.com/Respect/Validation) does support your use case, but you have to mix [Each](https://github.com/Respect/Validation/blob/master/docs/Each.md), [KeySet](https://github.com/Respect/Validation/blob/master/docs/KeySet.md) and [Key](https://github.com/Respect/Validation/blob/master/docs/Key.md) to obtain your desidered result.

The solution is the following:

```php
$validators = [
  'date' => v::date()->notEmpty(),
  'arrayOfObjects' => v::each(
      v::keySet(
        v::key('id', v::intVal()->positive()->notEmpty()),
        v::key('name', v::alnum()->notEmpty())
      )
  )
];
```

Hope it helps you. 😄

**Comment by jtiala** [comment]
Thanks for your answer and help! I guess I should have checked out the Respect Validation documentation more carefully.
